//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rlhTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public activity_master()
        {
            this.activity_schedule_master = new HashSet<activity_schedule_master>();
            this.client_city_activity_master = new HashSet<client_city_activity_master>();
            this.package_city_activity_master = new HashSet<package_city_activity_master>();
        }
    
        public int C_AM_id { get; set; }
        public int C_CM_id { get; set; }
        public string Activity_Name { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public int Duration { get; set; }
        public string Description { get; set; }
    
        public virtual activity_image_master activity_image_master { get; set; }
        public virtual city_master city_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activity_schedule_master> activity_schedule_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_city_activity_master> client_city_activity_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_city_activity_master> package_city_activity_master { get; set; }
    }
}
