//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rlhTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class destination_image_master
    {
        public int C_DM_id { get; set; }
        public string Image_URL { get; set; }
    
        public virtual destination_master destination_master { get; set; }
    }
}
