//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rlhTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favourite_master
    {
        public int C_FM_id { get; set; }
        public int C_CUM_id { get; set; }
        public int C_CPM_id { get; set; }
        public int C_PM_id { get; set; }
        public System.DateTime Chosen_Date { get; set; }
    
        public virtual client_master client_master { get; set; }
        public virtual client_package_master client_package_master { get; set; }
        public virtual package_master package_master { get; set; }
    }
}
