//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rlhTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class query_master
    {
        public int C_QM_id { get; set; }
        public int C_CUM_id { get; set; }
        public int Query_Status { get; set; }
        public int No_Of_Days { get; set; }
        public double Budget { get; set; }
        public int No_Of_Person { get; set; }
        public double Mobile { get; set; }
        public string Email_id { get; set; }
        public Nullable<int> C_PM_id { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Seen_Date { get; set; }
        public sbyte Seen_Flag { get; set; }
        public string Seen_By { get; set; }
    
        public virtual client_master client_master { get; set; }
        public virtual package_master package_master { get; set; }
    }
}
