//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rlhTest.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class city_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public city_master()
        {
            this.activity_master = new HashSet<activity_master>();
            this.client_package_city_master = new HashSet<client_package_city_master>();
            this.package_city_activity_master = new HashSet<package_city_activity_master>();
            this.package_city_master = new HashSet<package_city_master>();
        }
    
        public int C_CM_id { get; set; }
        public int C_Co_DM_id { get; set; }
        public string City_Name { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> Activity_Hours { get; set; }
        public int C_CDM_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activity_master> activity_master { get; set; }
        public virtual country_dest_master country_dest_master { get; set; }
        public virtual cont_destination_master cont_destination_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_package_city_master> client_package_city_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_city_activity_master> package_city_activity_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_city_master> package_city_master { get; set; }
    }
}
