//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rlhTest.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rlh_dataEntities2 : DbContext
    {
        public rlh_dataEntities2()
            : base("name=rlh_dataEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity_image_master> activity_image_master { get; set; }
        public virtual DbSet<activity_master> activity_master { get; set; }
        public virtual DbSet<activity_schedule_master> activity_schedule_master { get; set; }
        public virtual DbSet<booking_master> booking_master { get; set; }
        public virtual DbSet<city_master> city_master { get; set; }
        public virtual DbSet<client_city_activity_master> client_city_activity_master { get; set; }
        public virtual DbSet<client_master> client_master { get; set; }
        public virtual DbSet<client_package_city_master> client_package_city_master { get; set; }
        public virtual DbSet<client_package_master> client_package_master { get; set; }
        public virtual DbSet<cont_destination_master> cont_destination_master { get; set; }
        public virtual DbSet<country_dest_master> country_dest_master { get; set; }
        public virtual DbSet<destination_image_master> destination_image_master { get; set; }
        public virtual DbSet<favourite_master> favourite_master { get; set; }
        public virtual DbSet<keyword_master> keyword_master { get; set; }
        public virtual DbSet<package_city_activity_master> package_city_activity_master { get; set; }
        public virtual DbSet<package_city_master> package_city_master { get; set; }
        public virtual DbSet<package_dest_master> package_dest_master { get; set; }
        public virtual DbSet<package_master> package_master { get; set; }
        public virtual DbSet<package_pick_month> package_pick_month { get; set; }
        public virtual DbSet<priviledge> priviledges { get; set; }
        public virtual DbSet<query_master> query_master { get; set; }
        public virtual DbSet<user_master> user_master { get; set; }
        public virtual DbSet<priviledgeuser_relate> priviledgeuser_relate { get; set; }
    }
}
