//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rlhTest.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_pick_month
    {
        public int C_PPM { get; set; }
        public int C_PM { get; set; }
        public string Package_Month { get; set; }
    
        public virtual package_master package_master { get; set; }
    }
}
