//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rlhTest.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public package_master()
        {
            this.booking_master = new HashSet<booking_master>();
            this.client_package_master = new HashSet<client_package_master>();
            this.favourite_master = new HashSet<favourite_master>();
            this.package_city_master = new HashSet<package_city_master>();
            this.package_dest_master = new HashSet<package_dest_master>();
            this.package_pick_month = new HashSet<package_pick_month>();
            this.keyword_master = new HashSet<keyword_master>();
        }
    
        public int C_PM_id { get; set; }
        public string Package_Name { get; set; }
        public string Package_Description { get; set; }
        public int No_of_Days { get; set; }
        public int Package_Price { get; set; }
        public sbyte Booking_Enabled_Flag { get; set; }
        public sbyte Customization_Allowed_Flag { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public Nullable<System.DateTime> Expiring_Date { get; set; }
        public Nullable<int> Booking_Count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_master> booking_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_package_master> client_package_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite_master> favourite_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_city_master> package_city_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_dest_master> package_dest_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_pick_month> package_pick_month { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<keyword_master> keyword_master { get; set; }
    }
}
