//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rlhTest.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class priviledgeuser_relate
    {
        public int C_PV_id { get; set; }
        public Nullable<int> C_UM_id { get; set; }
    
        public virtual priviledge priviledge { get; set; }
        public virtual user_master user_master { get; set; }
    }
}
