//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rlhTest.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class priviledge
    {
        public int C_PV_id { get; set; }
        public string Priviledge_Name { get; set; }
        public sbyte Priviledge_Value { get; set; }
    
        public virtual priviledgeuser_relate priviledgeuser_relate { get; set; }
    }
}
