//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rlhTest.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class query_master
    {
        public int C_QM_id { get; set; }
        public Nullable<int> C_CUM_id { get; set; }
        public Nullable<int> Query_Status { get; set; }
        public Nullable<int> No_Of_Days { get; set; }
        public Nullable<double> Budget { get; set; }
        public Nullable<int> No_Of_Person { get; set; }
        public Nullable<double> Mobile { get; set; }
        public string Email_id { get; set; }
        public Nullable<int> C_PM_id { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Seen_Date { get; set; }
        public Nullable<sbyte> Seen_Flag { get; set; }
        public string Seen_By { get; set; }
        public string Client_Name { get; set; }
        public string Destination { get; set; }
    }
}
